name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

# Add this section to force Node 24
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
